#:schema node_modules/wrangler/config-schema.json
name = "get-cities"
main = "src/index.js"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

routes = [
	{ pattern = "cities.yack.one", custom_domain = true }
]